import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import ApolloProviders from "@/apollo/components/ApolloProviders";
import ThemeRegistry from "@/provider/themeCustom/ThemeRegistry";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import ReactQueryProvider from "@/provider/reactQuery/ReactQueryProvider";
import { Suspense } from "react";
import SessionProvider from "@/components/providers/SessionProvider";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type DashboardLayoutProps = {
  children: React.ReactNode;
};

const RootLayout: React.FC<DashboardLayoutProps> = (props) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main">
          <div className="gradient" />
        </div>
        <main>
          <ReactQueryProvider>
            <Suspense fallback={null}>
              <ApolloProviders>
                <ReduxProvider>
                  <SessionProvider>
                    <ThemeRegistry options={{ key: "mui", prepend: true }}>
                      <Header />
                      <div className="selection:bg-red-300 min-h-screen">
                        {props.children}
                      </div>
                      <Footer />
                    </ThemeRegistry>
                  </SessionProvider>
                </ReduxProvider>
              </ApolloProviders>
            </Suspense>
          </ReactQueryProvider>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
